### ISSUE TITLE
poprawki 2

### ISSUE THREAD

**Issue by zdolny** [tomsloni/kodilla-7-6#3]
w package.json brakuje watcha

zmiany wrzuc juz do mastera i dorzuc komantarz do tego issue

**Comment by tomsloni** [comment]
dodane

**Comment by zdolny** [comment]
Jak wpisuje `grunt` w konsoli to nie odpala sie `browserSync`. Powod, dlaczego tak sie dzieje mozesz znalezc w dokumentacji, dokladnie w tym miejscu: https://browsersync.io/docs/grunt#grunt-watch

**Comment by zdolny** [comment]
przy odpaleniu grunta nie wygenerowal mi sie zminifikowany obrazek i css dostal zla nazwe i sie nie zalaczyl. Mozesz to przetestowac u siebie usuwajac folder `css` i `images/build`, a nastepnie odpalajac grunta
